import { z } from "zod";
import { protectedProcedure, router } from "../_core/trpc";
import { createVideoProject, getUserVideoProjects, getVideoProjectById, updateVideoProject, createScene, getProjectScenes, addToProcessingQueue } from "../db";
import { analyzeStoryIntoScenes } from "../services/localSceneAnalyzer";

const CreateProjectSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  text: z.string().min(10, "Story text must be at least 10 characters").max(30000, "Story text cannot exceed 30,000 characters"),
});

const AnalyzeTextSchema = z.object({
  projectId: z.number(),
  text: z.string().max(30000, "Story text cannot exceed 30,000 characters"),
});

export const videoRouter = router({
  // Create a new video project
  createProject: protectedProcedure
    .input(CreateProjectSchema)
    .mutation(async ({ ctx, input }) => {
      if (!ctx.user?.id) throw new Error("User not authenticated");
      
      const project = await createVideoProject(ctx.user.id, {
        title: input.title,
        description: input.description,
        originalText: input.text,
        status: "draft",
      });
      
      return project;
    }),

  // Get all projects for the current user
  listProjects: protectedProcedure.query(async ({ ctx }) => {
    if (!ctx.user?.id) throw new Error("User not authenticated");
    return getUserVideoProjects(ctx.user.id);
  }),

  // Get a specific project with its scenes
  getProject: protectedProcedure
    .input(z.object({ projectId: z.number() }))
    .query(async ({ ctx, input }) => {
      if (!ctx.user?.id) throw new Error("User not authenticated");
      
      const project = await getVideoProjectById(input.projectId);
      if (!project || project.userId !== ctx.user.id) {
        throw new Error("Project not found or access denied");
      }
      
      const projectScenes = await getProjectScenes(input.projectId);
      return { project, scenes: projectScenes };
    }),

  // Analyze text and generate scenes
  analyzeAndGenerateScenes: protectedProcedure
    .input(AnalyzeTextSchema)
    .mutation(async ({ ctx, input }) => {
      if (!ctx.user?.id) throw new Error("User not authenticated");
      
      const project = await getVideoProjectById(input.projectId);
      if (!project || project.userId !== ctx.user.id) {
        throw new Error("Project not found or access denied");
      }
      
      // Update project status to processing
      await updateVideoProject(input.projectId, { status: "processing" });
      
      // Use local text analyzer to generate scenes (no external LLM needed)
      let sceneData;
      try {
        console.log("[Video] Using local scene analyzer (no LLM required)");
        const analyzedScenes = analyzeStoryIntoScenes(input.text, 20);
        
        if (!analyzedScenes || analyzedScenes.length === 0) {
          throw new Error("No scenes generated by local analyzer");
        }
        
        sceneData = {
          scenes: analyzedScenes.map(scene => ({
            title: scene.title,
            description: scene.description,
            imagePrompt: scene.imagePrompt,
            textContent: scene.textContent,
          })),
        };
        
        console.log(`[Video] Local analyzer generated ${sceneData.scenes.length} scenes`);
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : "Failed to analyze story";
        console.error("[Video] Scene analysis error:", errorMsg);
        await updateVideoProject(input.projectId, { status: "failed", errorMessage: errorMsg });
        throw new Error(errorMsg);
      }
      
      // Create scenes in the database
      const scenes = [];
      for (let i = 0; i < sceneData.scenes.length; i++) {
        const sceneInfo = sceneData.scenes[i];
        const scene = await createScene({
          projectId: input.projectId,
          sceneNumber: i + 1,
          title: sceneInfo.title,
          description: sceneInfo.description,
          textContent: sceneInfo.textContent,
          imagePrompt: sceneInfo.imagePrompt,
          status: "pending",
        });
        scenes.push(scene);
        
        // Add to processing queue
        await addToProcessingQueue({
          projectId: input.projectId,
          sceneId: (scene as any).insertId,
          taskType: "generate_image",
          status: "pending",
          priority: i,
        });
      }
      
      // Update project with scene count
      await updateVideoProject(input.projectId, { sceneCount: sceneData.scenes.length });
      
      return { scenes: sceneData.scenes, projectId: input.projectId };
    }),
});
